# Generated by Django 4.2.13 on 2024-07-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('DUBLIN_1', 'Dublin 1'), ('DUBLIN_2', 'Dublin 2'), ('DUBLIN_3', 'Dublin 3'), ('DUBLIN_4', 'Dublin 4'), ('DUBLIN_5', 'Dublin 5'), ('DUBLIN_6', 'Dublin 6'), ('DUBLIN_6W', 'Dublin 6W'), ('DUBLIN_7', 'Dublin 7'), ('DUBLIN_8', 'Dublin 8'), ('DUBLIN_9', 'Dublin 9'), ('DUBLIN_10', 'Dublin 10'), ('DUBLIN_11', 'Dublin 11'), ('DUBLIN_12', 'Dublin 12'), ('DUBLIN_13', 'Dublin 13'), ('DUBLIN_14', 'Dublin 14'), ('DUBLIN_15', 'Dublin 15'), ('DUBLIN_16', 'Dublin 16'), ('DUBLIN_17', 'Dublin 17'), ('DUBLIN_18', 'Dublin 18'), ('DUBLIN_20', 'Dublin 20'), ('DUBLIN_22', 'Dublin 22'), ('DUBLIN_24', 'Dublin 24'), ('DUN_LAOGHAIRE_RATHDOWN', 'Dún Laoghaire–Rathdown'), ('FINGAL', 'Fingal'), ('SOUTH_DUBLIN', 'South Dublin')], max_length=50),
        ),
    ]
