# Generated by Django 4.2.13 on 2024-07-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='events/images/default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
