# Generated by Django 4.2.13 on 2024-08-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
    ]
