# Generated by Django 4.2.13 on 2024-08-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entrance_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
